import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';

const $=s=>document.querySelector(s), viewer=$('#viewer');
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xe9eee8,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;viewer.append(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.01,100);scene.background=new THREE.Color(0xe9eee8);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.35;controls.maxDistance=12;
const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.04);scene.environment=env.texture;room.dispose();pmrem.dispose();
scene.add(new THREE.HemisphereLight(0xf5fcff,0x677463,2));const keyLight=new THREE.DirectionalLight(0xffffff,2);keyLight.position.set(-3,6,4);scene.add(keyLight);
const grid=new THREE.GridHelper(5,20,0xc6d1c5,0xdde3da);grid.position.y=-.025;scene.add(grid);
const holder=new THREE.Group();scene.add(holder);const loader=new GLTFLoader();
const groups={},slots={},originals=new Map(),materialBackups=new Map(),replacements=new Map(),groupNodeToSlot=new Map();
const bodyKeys=new Set(['tank','seat','seat_rear','tail','tail_left','tail_right','fairing_left','fairing_right','front_cowl','front_fender','lower_cowl']);
let registry,currentVehicle,root,selected='tank',scale=1,isolation=false,explode=0,loadEpoch=0,replaceEpoch=0,wrapEpoch=0;
const state={ready:false,errors:[]};window.addEventListener('error',e=>state.errors.push(e.message));window.addEventListener('unhandledrejection',e=>state.errors.push(String(e.reason)));

function resize(){const {width,height}=viewer.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();}
new ResizeObserver(resize).observe(viewer);function render(){controls.update();renderer.render(scene,camera);requestAnimationFrame(render);}render();
function meshes(node){const out=[];node?.traverse(o=>{if(o.isMesh)out.push(o);});return out;}
function materials(mesh){return Array.isArray(mesh.material)?mesh.material:[mesh.material];}
function status(text){$('#status').textContent=text;}
function setView(kind='overview'){const p={overview:[3.2,1.55,3.5],left:[0,1.05,-4.5],right:[0,1.05,4.5],front:[4.5,1.05,0]};controls.target.set(0,.63,0);camera.position.fromArray(p[kind]);if(camera.aspect<1)camera.position.multiplyScalar(1.25);controls.update();}
function disposeMaterial(mat){if(mat?.userData?.previewMap)mat.userData.previewMap.dispose();mat?.dispose?.();}
function clearRecord(){replaceEpoch++;wrapEpoch++;for(const rep of replacements.values())disposeNode(rep.holder);replacements.clear();if(root){holder.remove(root);disposeNode(root);}root=undefined;for(const key of Object.keys(groups))delete groups[key];for(const key of Object.keys(slots))delete slots[key];originals.clear();materialBackups.clear();groupNodeToSlot.clear();$('#part').replaceChildren();holder.position.set(0,0,0);holder.scale.setScalar(1);}
function disposeNode(node){node?.traverse(o=>{if(o.isMesh){o.geometry?.dispose?.();for(const m of materials(o))disposeMaterial(m);}});node?.removeFromParent?.();}
function highlight(){for(const [key,g] of Object.entries(groups))for(const m of meshes(g))for(const mat of materials(m))if(mat?.emissive){mat.emissive.set(key===selected?0x194a32:0);mat.emissiveIntensity=key===selected?.22:0;}}
function findSlotForObject(object){let o=object;while(o&&o!==root){const key=groupNodeToSlot.get(o);if(key)return key;o=o.parent;}return undefined;}
function applyVisibility(){if(!root)return;root.traverse(o=>{if(o.isMesh){const key=findSlotForObject(o);o.visible=!isolation||key===selected;}});for(const [key,g] of Object.entries(groups)){g.visible=!g.userData.hidden&&(!isolation||key===selected);const rep=replacements.get(key);if(rep)for(const child of originals.get(key).children)child.visible=false;}$('#isolate').classList.toggle('active',isolation);$('#isolate').textContent=isolation?'返回整车':'单独查看';grid.visible=!isolation;}
function focusPart(){const g=groups[selected];if(!g)return;const box=new THREE.Box3().setFromObject(g),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length(),dir=camera.position.clone().sub(controls.target).normalize();controls.target.copy(center);camera.position.copy(center).addScaledVector(dir,Math.max(size,.08)*1.8/Math.min(camera.aspect,1));controls.update();}
function select(key){if(!groups[key])return;selected=key;wrapEpoch++;$('#part').value=key;$('#selectedName').textContent=slots[key].label;$('#partId').textContent=`${slots[key].slotId} · ${currentVehicle.vehicleId}`;highlight();if(isolation){applyVisibility();focusPart();}syncReplacement();$('#hide').textContent=groups[key].userData.hidden?'显示部件':'隐藏部件';}
function spread(value){explode=+value;for(const [key,g] of Object.entries(groups)){const offset=slots[key].explodeOffset||[0,0,0];g.position.copy(originals.get(key).position).addScaledVector(new THREE.Vector3(...offset),explode/100/scale);}$('#explode').value=explode;$('#explodeValue').textContent=explode+'%';root?.updateMatrixWorld(true);}
function restoreLook(key){const record=originals.get(key);if(!record)return;for(const mesh of record.meshes){for(const mat of materials(mesh))disposeMaterial(mat);const clones=materialBackups.get(mesh).map(mat=>mat.clone());mesh.material=clones.length===1?clones[0]:clones;const uv=mesh.userData.originalUV;if(uv)mesh.geometry.setAttribute('uv',uv.clone());else mesh.geometry.deleteAttribute('uv');}highlight();}
function paint(color){if(replacements.has(selected)){status('替换件保留自己的材质，请先恢复原件。');return;}restoreLook(selected);for(const mesh of originals.get(selected).meshes)for(const mat of materials(mesh)){mat.color?.set(color);mat.map=null;mat.needsUpdate=true;}highlight();status(`已修改${slots[selected].label}的颜色`);}
function applyWrap(image,key){if(!bodyKeys.has(key)){status('当前部件不属于车壳贴膜区域。');return;}if(replacements.has(key)){status('请先恢复原件再预览贴膜。');return;}restoreLook(key);const parts=originals.get(key).meshes,box=new THREE.Box3();for(const mesh of parts){mesh.geometry.computeBoundingBox();box.union(mesh.geometry.boundingBox.clone().applyMatrix4(mesh.matrixWorld));}const size=box.getSize(new THREE.Vector3()),top=['tank','seat','seat_rear','front_fender'].includes(key),texture=new THREE.CanvasTexture(image);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=renderer.capabilities.getMaxAnisotropy();for(const mesh of parts){const pos=mesh.geometry.attributes.position,uv=new Float32Array(pos.count*2),p=new THREE.Vector3();for(let i=0;i<pos.count;i++){p.fromBufferAttribute(pos,i).applyMatrix4(mesh.matrixWorld);uv[i*2]=(p.x-box.min.x)/Math.max(size.x,.001);uv[i*2+1]=top?(p.z-box.min.z)/Math.max(size.z,.001):(p.y-box.min.y)/Math.max(size.y,.001);}mesh.geometry.setAttribute('uv',new THREE.BufferAttribute(uv,2));for(const mat of materials(mesh)){mat.map=texture;mat.userData.previewMap=texture;mat.color?.set(0xffffff);mat.needsUpdate=true;}}highlight();status(`已显示贴膜预览：${slots[key].label}`);}
function stripe(){const c=document.createElement('canvas');c.width=c.height=1024;const x=c.getContext('2d');x.fillStyle=$('#color').value;x.fillRect(0,0,1024,1024);x.fillStyle='#f3f1e8';x.beginPath();x.moveTo(70,0);x.lineTo(300,0);x.lineTo(810,1024);x.lineTo(580,1024);x.fill();x.fillStyle='#162822';x.beginPath();x.moveTo(350,0);x.lineTo(415,0);x.lineTo(925,1024);x.lineTo(860,1024);x.fill();applyWrap(c,selected);}
function restorePart(key){const rep=replacements.get(key);if(rep){disposeNode(rep.holder);replacements.delete(key);}const record=originals.get(key);if(record)for(const child of record.children)child.visible=true;applyVisibility();syncReplacement();}
function syncReplacement(){const cfg=slots[selected],rep=replacements.get(selected),enabled=!!cfg?.replaceable;$('#replacementFile').disabled=!enabled;$('#replacementLabel').classList.toggle('disabled',!enabled);$('#restorePart').disabled=!enabled;$('#replaceState').textContent=enabled?'已预留换件接口':'仅展示';$('#replacementName').textContent=enabled?(rep?rep.name:'未导入替换件'):(cfg?.replacementPolicy?.reason||'当前部件不开放替换');for(const [id,value] of Object.entries({replaceScale:1,replaceX:0,replaceY:0,replaceZ:0,replaceTurn:0}))$('#'+id).value=rep?.settings[id]??value;}
function updateReplacement(){const rep=replacements.get(selected);if(!rep)return;for(const id of ['replaceScale','replaceX','replaceY','replaceZ','replaceTurn'])rep.settings[id]=+$('#'+id).value;const s=rep.settings;rep.holder.position.copy(rep.center).add(new THREE.Vector3(s.replaceX,s.replaceY,s.replaceZ).multiplyScalar(1/scale));rep.holder.scale.setScalar(s.replaceScale);rep.holder.rotation.y=s.replaceTurn*Math.PI/180;}
async function importReplacement(file){if(!file)return;const key=selected,cfg=slots[key],epoch=++replaceEpoch;if(!cfg?.replaceable){status('当前部件只用于展示，没有开放换件。');return;}try{if(file.size>150*1024*1024)throw Error('文件超过150MB，请先精简');const data=await file.arrayBuffer(),gltf=await loader.parseAsync(data,'');if(epoch!==replaceEpoch)return;const content=gltf.scene,bb=new THREE.Box3().setFromObject(content),sourceSize=bb.getSize(new THREE.Vector3());if(!Number.isFinite(sourceSize.length())||sourceSize.length()<1e-6)throw Error('模型为空或尺寸无效');restorePart(key);const targetBox=new THREE.Box3();for(const mesh of originals.get(key).meshes){mesh.geometry.computeBoundingBox();targetBox.union(mesh.geometry.boundingBox.clone().applyMatrix4(mesh.matrixWorld));}const targetSize=targetBox.getSize(new THREE.Vector3()),center=groups[key].worldToLocal(targetBox.getCenter(new THREE.Vector3())),fit=Math.max(targetSize.x,targetSize.y,targetSize.z)/Math.max(sourceSize.x,sourceSize.y,sourceSize.z)/scale,sourceCenter=bb.getCenter(new THREE.Vector3());content.position.addScaledVector(sourceCenter,-1);const fitNode=new THREE.Group();fitNode.scale.setScalar(fit);fitNode.add(content);const repHolder=new THREE.Group();repHolder.add(fitNode);repHolder.position.copy(center);groups[key].add(repHolder);replacements.set(key,{holder:repHolder,center,name:file.name,settings:{replaceScale:1,replaceX:0,replaceY:0,replaceZ:0,replaceTurn:0}});applyVisibility();syncReplacement();highlight();status(`已替换${cfg.label}，请校准位置`);}catch(e){status(`替换失败：${e.message}；原件保持不变`);}}
function reset(){replaceEpoch++;wrapEpoch++;for(const key of Object.keys(groups)){restorePart(key);restoreLook(key);groups[key].userData.hidden=false;}isolation=false;spread(0);applyVisibility();controls.autoRotate=false;$('#auto').classList.remove('active');$('#wrapFile').value='';$('#replacementFile').value='';select(currentVehicle.defaultSlotKey in groups?currentVehicle.defaultSlotKey:Object.keys(groups)[0]);setView();status('已恢复当前车型的原模型、材质和位置');}
async function loadVehicle(vehicleId){const epoch=++loadEpoch,stateVehicle=registry.vehicles.find(v=>v.vehicleId===vehicleId);if(!stateVehicle)return;state.ready=false;$('#controls').inert=true;$('#loading').hidden=false;$('#loading').innerHTML='<b>正在加载整车</b><span id="progress">准备中…</span>';clearRecord();currentVehicle=stateVehicle;$('#vehicle').value=vehicleId;$('#vehicleMeta').textContent=`${stateVehicle.templateId} / ${stateVehicle.templateVersion}`;$('#identityStatus').textContent=stateVehicle.identityStatus==='pending'?'车型信息待核实':'车型按文件名记录';try{const gltf=await loader.loadAsync(stateVehicle.modelUrl,e=>{const p=$('#progress');if(p)p.textContent=e.total?Math.round(e.loaded/e.total*100)+'%':'读取模型…';});if(epoch!==loadEpoch){disposeNode(gltf.scene);return;}root=gltf.scene;holder.add(root);root.updateMatrixWorld(true);const bb=new THREE.Box3().setFromObject(root),size=bb.getSize(new THREE.Vector3());scale=2.6/Math.max(size.x,size.y,size.z);holder.scale.setScalar(scale);holder.position.set(-(bb.min.x+bb.max.x)/2*scale,-bb.min.y*scale,-(bb.min.z+bb.max.z)/2*scale);root.updateMatrixWorld(true);
 if(stateVehicle.templateId==='KAW-DEMO-TPL-001'){const glass=root.getObjectByName('windscreen_surface');if(glass){glass.material=glass.material.clone();Object.assign(glass.material,{alphaTest:0,transparent:true,opacity:.32,roughness:.18,depthWrite:false});glass.material.color.set(0x536673);}}
 for(const cfg of stateVehicle.slots){const group=root.getObjectByName(cfg.groupNode);if(!group)throw Error(`模型缺少部件节点：${cfg.groupNode}`);groups[cfg.slotKey]=group;slots[cfg.slotKey]=cfg;groupNodeToSlot.set(group,cfg.slotKey);const mm=meshes(group);originals.set(cfg.slotKey,{position:group.position.clone(),children:[...group.children],meshes:mm});for(const mesh of mm){mesh.geometry=mesh.geometry.clone();mesh.userData.originalUV=mesh.geometry.attributes.uv?.clone();materialBackups.set(mesh,materials(mesh).map(mat=>mat.clone()));const clones=materials(mesh).map(mat=>mat.clone());mesh.material=clones.length===1?clones[0]:clones;}const opt=document.createElement('option');opt.value=cfg.slotKey;opt.textContent=cfg.label;$('#part').append(opt);}
 $('#count').textContent=`${stateVehicle.slots.length} 个部件位置`;$('#loading').hidden=true;$('#controls').inert=false;selected=stateVehicle.defaultSlotKey in groups?stateVehicle.defaultSlotKey:Object.keys(groups)[0];isolation=false;explode=0;select(selected);spread(0);applyVisibility();resize();setView();status(`已切换到 ${stateVehicle.displayName}`);state.ready=true;
 }catch(e){state.errors.push(e.message);$('#loading').innerHTML='<b>模型加载失败</b>';const p=document.createElement('p');p.textContent=e.message;$('#loading').append(p);}}

$('#vehicle').onchange=e=>loadVehicle(e.target.value);$('#part').onchange=e=>select(e.target.value);$('#explode').oninput=e=>spread(e.target.value);$('#isolate').onclick=()=>{isolation=!isolation;applyVisibility();if(isolation)focusPart();else setView();};$('#hide').onclick=()=>{groups[selected].userData.hidden=!groups[selected].userData.hidden;applyVisibility();select(selected);};$('#show').onclick=()=>{isolation=false;for(const g of Object.values(groups))g.userData.hidden=false;applyVisibility();select(selected);setView();};$('#reset').onclick=reset;
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#auto').onclick=()=>{$('#auto').classList.toggle('active');controls.autoRotate=!controls.autoRotate;};document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{$('#color').value=b.dataset.color;paint(b.dataset.color);});$('#color').oninput=e=>paint(e.target.value);$('#stripe').onclick=stripe;$('#restoreLook').onclick=()=>{wrapEpoch++;restoreLook(selected);status('已恢复当前部件外观');};$('#restorePart').onclick=()=>{replaceEpoch++;restorePart(selected);status('已恢复原件');};
$('#wrapFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;const key=selected,epoch=++wrapEpoch;try{if(file.size>20*1024*1024)throw Error('图片超过20MB');const bitmap=await createImageBitmap(file);if(epoch!==wrapEpoch){bitmap.close();return;}const c=document.createElement('canvas'),ratio=Math.min(1,2048/Math.max(bitmap.width,bitmap.height));c.width=Math.round(bitmap.width*ratio);c.height=Math.round(bitmap.height*ratio);c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();applyWrap(c,key);}catch(err){status('贴膜图片读取失败：'+err.message);}};
$('#replacementFile').onchange=e=>importReplacement(e.target.files[0]);for(const id of ['replaceScale','replaceX','replaceY','replaceZ','replaceTurn'])$('#'+id).oninput=updateReplacement;
const ray=new THREE.Raycaster();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!root||!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);for(const hit of ray.intersectObject(root,true)){const key=findSlotForObject(hit.object);if(key){select(key);break;}}});
window.demoInspect=()=>({ready:state.ready,errors:state.errors,currentVehicle:currentVehicle?.vehicleId,templateVersion:currentVehicle?.templateVersion,selected,explode,isolation,replacements:[...replacements.keys()],slots:Object.fromEntries(Object.keys(groups).map(k=>[k,{slotId:slots[k].slotId,replaceable:slots[k].replaceable,visible:groups[k].visible,meshes:meshes(groups[k]).length}]))});

try{registry=await (await fetch('./vehicles.json')).json();for(const vehicle of registry.vehicles){const opt=document.createElement('option');opt.value=vehicle.vehicleId;opt.textContent=vehicle.displayName;$('#vehicle').append(opt);}await loadVehicle(registry.vehicles[0].vehicleId);}catch(e){state.errors.push(e.message);$('#loading').innerHTML=`<b>配置加载失败</b><p>${e.message}</p>`;}
