import type { Part } from '@motorcycle-ai/shared';
import type { KnowledgeSnippet } from './types.js';

type SamplePartFixture = Omit<Part, 'thumbnailUrl'>;

const samplePartFixtures: SamplePartFixture[] = [
  {
    partId: 'demo-part-01',
    name: '碳纤维尾段排气',
    brand: 'Akrapovič',
    partType: 'exhaust',
    fitModels: ['川崎 Ninja 400 2018-2023'],
    price: 5980,
    source: '品牌适配目录',
    sourceUrl: 'https://example.com/catalog/akrapovic-ninja400',
  },
  {
    partId: 'demo-part-02',
    name: 'R-11 全段排气',
    brand: 'Yoshimura',
    partType: 'exhaust',
    fitModels: ['本田 CBR500R 2019-2023'],
    price: 7280,
    source: '品牌适配目录',
    sourceUrl: 'https://example.com/catalog/yoshimura-cbr500r',
  },
  {
    partId: 'demo-part-03',
    name: 'LV-10 尾段排气',
    brand: 'LeoVince',
    partType: 'exhaust',
    fitModels: ['KTM Duke 390 2021-2024'],
    price: 3380,
    source: '品牌适配目录',
    sourceUrl: 'https://example.com/catalog/leovince-duke390',
  },
  {
    partId: 'demo-part-04',
    name: 'Racing 双泡风挡',
    brand: 'Puig',
    partType: 'windshield',
    fitModels: ['川崎 Ninja 400 2018-2023'],
    price: 780,
    source: '风挡适配目录',
    sourceUrl: 'https://example.com/catalog/puig-ninja400',
  },
  {
    partId: 'demo-part-05',
    name: 'Touring 加高风挡',
    brand: 'Puig',
    partType: 'windshield',
    fitModels: ['宝马 R 1250 GS 2019-2024'],
    price: 1280,
    source: '风挡适配目录',
    sourceUrl: 'https://example.com/catalog/puig-r1250gs',
  },
  {
    partId: 'demo-part-06',
    name: 'Airflow 可调风挡',
    brand: 'GIVI',
    partType: 'windshield',
    fitModels: ['本田 NC750X 2021-2024'],
    price: 1680,
    source: '风挡适配目录',
    sourceUrl: 'https://example.com/catalog/givi-nc750x',
  },
  {
    partId: 'demo-part-07',
    name: 'V35N 35L 边箱套装',
    brand: 'GIVI',
    partType: 'saddlebag',
    fitModels: ['川崎 Versys 650 2015-2024'],
    price: 5280,
    source: '边箱支架目录',
    sourceUrl: 'https://example.com/catalog/givi-versys650',
  },
  {
    partId: 'demo-part-08',
    name: 'SH36 36L 边箱套装',
    brand: 'SHAD',
    partType: 'saddlebag',
    fitModels: ['本田 CB500X 2019-2023'],
    price: 4680,
    source: '边箱支架目录',
    sourceUrl: 'https://example.com/catalog/shad-cb500x',
  },
  {
    partId: 'demo-part-09',
    name: 'Road 6 运动旅行轮胎',
    brand: 'Michelin',
    partType: 'other',
    fitModels: ['雅马哈 MT-07 2021-2024'],
    price: 1980,
    source: '轮胎规格目录',
    sourceUrl: 'https://example.com/catalog/michelin-road6',
  },
  {
    partId: 'demo-part-10',
    name: 'STX 46 后减震',
    brand: 'Öhlins',
    partType: 'other',
    fitModels: ['川崎 Ninja 400 2018-2023'],
    price: 6880,
    source: '减震安装说明',
    sourceUrl: 'https://example.com/catalog/ohlins-ninja400',
  },
];

export const sampleParts: Part[] = samplePartFixtures.map((part) => ({
  ...part,
  thumbnailUrl: `https://example.com/thumbnails/${part.partId}.webp`,
}));

export const sampleKnowledge: KnowledgeSnippet[] = [
  {
    knowledgeId: 'demo-kn-01',
    title: 'Ninja 400 服务手册：冷启动',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/ninja400-cold-start',
    content: '冷车启动困难和怠速熄火时，先检查蓄电池电压、火花塞以及节气门怠速空气通道。',
  },
  {
    knowledgeId: 'demo-kn-02',
    title: 'YZF-R3 服务手册：高转动力',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/r3-high-rpm',
    content: '加速无力或高转顿挫时，检查空气滤芯进气阻力、燃油压力和喷油器状态。',
  },
  {
    knowledgeId: 'demo-kn-03',
    title: 'CB500X 服务手册：液压制动',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/cb500x-brake',
    content: '刹车手感变软时检查制动液液位、管路泄漏并按维修顺序排出系统空气。',
  },
  {
    knowledgeId: 'demo-kn-04',
    title: 'Duke 390 维护手册：链条',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/duke390-chain',
    content: '链条异响和收油顿挫常与松弛量过大、润滑不足或链轮磨损有关。',
  },
  {
    knowledgeId: 'demo-kn-05',
    title: 'Z400 服务手册：冷却系统',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/z400-cooling',
    content: '水温过高且风扇不转时，依次检查冷却液、保险丝、风扇继电器和电机供电。',
  },
];
