import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';

const $=s=>document.querySelector(s), viewer=$('#viewer');
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0xe9eee8,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;viewer.append(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.01,100);scene.background=new THREE.Color(0xe9eee8);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=.35;controls.maxDistance=12;
const pmrem=new THREE.PMREMGenerator(renderer), room=new RoomEnvironment();const env=pmrem.fromScene(room,.04);scene.environment=env.texture;room.dispose();pmrem.dispose();
scene.add(new THREE.HemisphereLight(0xf5fcff,0x677463,2));const light=new THREE.DirectionalLight(0xffffff,2);light.position.set(-3,6,4);scene.add(light);
const grid=new THREE.GridHelper(5,20,0xc6d1c5,0xdde3da);grid.position.y=-.025;scene.add(grid);
const holder=new THREE.Group();scene.add(holder);
const loader=new GLTFLoader(), groups={}, originals=new Map(), mats=new Map(), replacements=new Map();
const bodyKeys=new Set(['tank','seat','tail','fairing_left','fairing_right','front_cowl','front_fender','lower_cowl']);
let root,manifest,scale=1,selected='tank',isolation=false,explode=0,wrapEpoch=0,replaceEpoch=0;
const state={ready:false,errors:[]};window.addEventListener('error',e=>state.errors.push(e.message));window.addEventListener('unhandledrejection',e=>state.errors.push(String(e.reason)));
const offsets={mirror_left:[.03,.10,-.22],mirror_right:[.03,.10,.22],windscreen:[.12,.14,0],front_cowl:[.13,.04,0],front_fender:[.10,.11,0],tank:[0,.18,0],seat:[-.05,.15,0],tail:[-.15,.09,0],fairing_left:[0,0,-.20],fairing_right:[0,0,.20],lower_cowl:[0,-.13,0],front_wheel:[.16,-.05,0],rear_wheel:[-.16,-.05,0],muffler:[-.05,-.05,.16],license_bracket:[-.15,.02,0]};
function resize(){const {width,height}=viewer.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();}
new ResizeObserver(resize).observe(viewer);
function render(){controls.update();renderer.render(scene,camera);requestAnimationFrame(render);}render();
function setView(kind='overview'){
 const positions={overview:[3.2,1.55,3.5],left:[0,1.05,-4.5],right:[0,1.05,4.5],front:[4.5,1.05,0]};
 controls.target.set(0,.63,0);camera.position.fromArray(positions[kind]);if(camera.aspect<1)camera.position.multiplyScalar(1.25);controls.update();
}
function meshes(node){const result=[];node.traverse(o=>{if(o.isMesh)result.push(o);});return result;}
function materials(mesh){return Array.isArray(mesh.material)?mesh.material:[mesh.material];}
function highlight(){for(const [key,g] of Object.entries(groups))for(const m of meshes(g))for(const mat of materials(m)){if(mat.emissive){mat.emissive.set(key===selected?0x194a32:0);mat.emissiveIntensity=key===selected?.22:0;}}}
function status(text){$('#status').textContent=text;}
function focusPart(){const box=new THREE.Box3().setFromObject(groups[selected]),center=box.getCenter(new THREE.Vector3()),size=box.getSize(new THREE.Vector3()).length();const dir=camera.position.clone().sub(controls.target).normalize();controls.target.copy(center);camera.position.copy(center).addScaledVector(dir,Math.max(size,.08)*1.8/Math.min(camera.aspect,1));controls.update();}
function select(key){if(!groups[key])return;selected=key;wrapEpoch++;$('#part').value=key;$('#selectedName').textContent=manifest[key].label;$('#partId').textContent=manifest[key].partId;highlight();if(isolation){applyVisibility();focusPart();}syncReplacement();$('#hide').textContent=groups[key].userData.hidden?'显示部件':'隐藏部件';}
function applyVisibility(){root.traverse(o=>{if(o.isMesh){let p=o,groupKey;while(p&&p!==root){if(groups[p.name]===p){groupKey=p.name;break;}p=p.parent;}o.visible=!isolation||groupKey===selected;}});for(const [k,g] of Object.entries(groups)){g.visible=!g.userData.hidden&&(!isolation||k===selected);const rep=replacements.get(k);if(rep)for(const child of originals.get(k).children)child.visible=false;}$('#isolate').classList.toggle('active',isolation);$('#isolate').textContent=isolation?'返回整车':'单独查看';grid.visible=!isolation;}
function spread(value){explode=+value;for(const [k,g] of Object.entries(groups)){const offset=offsets[k]||[0,0,0];g.position.copy(originals.get(k).position).addScaledVector(new THREE.Vector3(...offset),explode/100/scale);}$('#explode').value=explode;$('#explodeValue').textContent=explode+'%';root.updateMatrixWorld(true);}
function disposeMaterial(mat){if(mat.userData.previewMap)mat.userData.previewMap.dispose();mat.dispose();}
function restoreLook(key){for(const m of originals.get(key).meshes){for(const mat of materials(m))disposeMaterial(mat);m.material=mats.get(m).map(mat=>mat.clone());if(m.material.length===1)m.material=m.material[0];const saved=m.userData.originalUV;if(saved)m.geometry.setAttribute('uv',saved.clone());else m.geometry.deleteAttribute('uv');}highlight();}
function paintable(key){return originals.get(key).meshes;}
function paint(color){if(replacements.has(selected)){status('替换件保留自己的材质；恢复原件后可改色。');return;}restoreLook(selected);for(const m of paintable(selected))for(const mat of materials(m)){mat.color?.set(color);mat.map=null;mat.needsUpdate=true;}highlight();status('已修改'+manifest[selected].label+'的颜色');}
function applyWrap(image,key){if(!bodyKeys.has(key)){status('贴膜请先选择油箱、整流罩、尾壳、车头外壳或前挡泥板。');return;}if(replacements.has(key)){status('请先恢复原件再预览贴膜。');return;}
 restoreLook(key);const parts=paintable(key);const box=new THREE.Box3();for(const m of parts){m.geometry.computeBoundingBox();box.union(m.geometry.boundingBox.clone().applyMatrix4(m.matrixWorld));}const size=box.getSize(new THREE.Vector3());
 const top=['tank','seat','front_fender'].includes(key), texture=new THREE.CanvasTexture(image);texture.colorSpace=THREE.SRGBColorSpace;texture.anisotropy=renderer.capabilities.getMaxAnisotropy();
 for(const mesh of parts){const pos=mesh.geometry.attributes.position,uv=new Float32Array(pos.count*2),p=new THREE.Vector3();for(let i=0;i<pos.count;i++){p.fromBufferAttribute(pos,i).applyMatrix4(mesh.matrixWorld);uv[i*2]=(p.x-box.min.x)/Math.max(size.x,.001);uv[i*2+1]=top?(p.z-box.min.z)/Math.max(size.z,.001):(p.y-box.min.y)/Math.max(size.y,.001);}mesh.geometry.setAttribute('uv',new THREE.BufferAttribute(uv,2));for(const mat of materials(mesh)){mat.map=texture;mat.userData.previewMap=texture;mat.color?.set(0xffffff);mat.needsUpdate=true;}}
 highlight();status('已显示图案贴膜：'+manifest[key].label+'（平面投影预览）');
}
function stripe(){const c=document.createElement('canvas');c.width=c.height=1024;const x=c.getContext('2d');x.fillStyle=$('#color').value;x.fillRect(0,0,1024,1024);x.fillStyle='#f3f1e8';x.beginPath();x.moveTo(70,0);x.lineTo(300,0);x.lineTo(810,1024);x.lineTo(580,1024);x.fill();x.fillStyle='#162822';x.beginPath();x.moveTo(350,0);x.lineTo(415,0);x.lineTo(925,1024);x.lineTo(860,1024);x.fill();applyWrap(c,selected);}
function restorePart(key){const r=replacements.get(key);if(r){r.holder.removeFromParent();for(const m of meshes(r.holder)){m.geometry.dispose();for(const mat of materials(m)){for(const v of Object.values(mat))if(v?.isTexture)v.dispose();mat.dispose();}}replacements.delete(key);}for(const c of originals.get(key).children)c.visible=true;applyVisibility();syncReplacement();}
function syncReplacement(){const r=replacements.get(selected);$('#replacementName').textContent=r?r.name:'未导入替换件';for(const [id,defaultValue] of Object.entries({replaceScale:1,replaceX:0,replaceY:0,replaceZ:0,replaceTurn:0}))$('#'+id).value=r?.settings[id]??defaultValue;}
function updateReplacement(){const r=replacements.get(selected);if(!r)return;for(const id of ['replaceScale','replaceX','replaceY','replaceZ','replaceTurn'])r.settings[id]=+$('#'+id).value;const s=r.settings;r.holder.position.copy(r.center).add(new THREE.Vector3(s.replaceX,s.replaceY,s.replaceZ).multiplyScalar(1/scale));r.holder.scale.setScalar(s.replaceScale);r.holder.rotation.y=s.replaceTurn*Math.PI/180;}
async function importReplacement(file){if(!file)return;const key=selected,epoch=++replaceEpoch;try{if(file.size>150*1024*1024)throw Error('文件超过 150MB，请先精简模型');const data=await file.arrayBuffer();const gltf=await loader.parseAsync(data,'');if(epoch!==replaceEpoch)return;const content=gltf.scene,bb=new THREE.Box3().setFromObject(content),size=bb.getSize(new THREE.Vector3());if(!Number.isFinite(size.length())||size.length()<1e-6)throw Error('模型为空或尺寸无效');restorePart(key);
 const targetBox=new THREE.Box3();for(const m of originals.get(key).meshes){m.geometry.computeBoundingBox();targetBox.union(m.geometry.boundingBox.clone().applyMatrix4(m.matrixWorld));}const targetSize=targetBox.getSize(new THREE.Vector3());const center=groups[key].worldToLocal(targetBox.getCenter(new THREE.Vector3()));
 const fit=Math.max(targetSize.x,targetSize.y,targetSize.z)/Math.max(size.x,size.y,size.z)/scale,sourceCenter=bb.getCenter(new THREE.Vector3());content.position.addScaledVector(sourceCenter,-1);const fitNode=new THREE.Group();fitNode.scale.setScalar(fit);fitNode.add(content);const repHolder=new THREE.Group();repHolder.add(fitNode);repHolder.position.copy(center);groups[key].add(repHolder);
 replacements.set(key,{holder:repHolder,center,name:file.name,settings:{replaceScale:1,replaceX:0,replaceY:0,replaceZ:0,replaceTurn:0}});applyVisibility();syncReplacement();highlight();status('已替换'+manifest[key].label+'，可展开“调整”校准位置');
 }catch(e){status('替换失败：'+e.message+'；原件保持不变');}}
function reset(){replaceEpoch++;wrapEpoch++;for(const k of Object.keys(groups)){restorePart(k);restoreLook(k);groups[k].userData.hidden=false;}isolation=false;spread(0);applyVisibility();controls.autoRotate=false;$('#auto').classList.remove('active');$('#wrapFile').value='';$('#replacementFile').value='';select('tank');setView();status('已恢复原模型、材质、位置和可见性');}
$('#part').onchange=e=>select(e.target.value);$('#explode').oninput=e=>spread(e.target.value);$('#isolate').onclick=()=>{isolation=!isolation;applyVisibility();if(isolation)focusPart();else setView();};$('#hide').onclick=()=>{groups[selected].userData.hidden=!groups[selected].userData.hidden;applyVisibility();select(selected);};$('#show').onclick=()=>{isolation=false;for(const g of Object.values(groups))g.userData.hidden=false;applyVisibility();select(selected);setView();};$('#reset').onclick=reset;
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#auto').onclick=()=>{$('#auto').classList.toggle('active');controls.autoRotate=!controls.autoRotate;};document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{$('#color').value=b.dataset.color;paint(b.dataset.color);});$('#color').oninput=e=>paint(e.target.value);$('#stripe').onclick=stripe;$('#restoreLook').onclick=()=>{wrapEpoch++;restoreLook(selected);status('已恢复当前部件的原始材质');};$('#restorePart').onclick=()=>{replaceEpoch++;restorePart(selected);status('已恢复原件');};
$('#wrapFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;const key=selected,epoch=++wrapEpoch;try{if(file.size>20*1024*1024)throw Error('图片超过 20MB');const bitmap=await createImageBitmap(file);if(epoch!==wrapEpoch){bitmap.close();return;}const c=document.createElement('canvas'),ratio=Math.min(1,2048/Math.max(bitmap.width,bitmap.height));c.width=Math.round(bitmap.width*ratio);c.height=Math.round(bitmap.height*ratio);c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();applyWrap(c,key);}catch(err){status('贴膜图片读取失败：'+err.message);}};
$('#replacementFile').onchange=e=>importReplacement(e.target.files[0]);for(const id of ['replaceScale','replaceX','replaceY','replaceZ','replaceTurn'])$('#'+id).oninput=updateReplacement;
const ray=new THREE.Raycaster();let down;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!root||!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const rect=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);for(const hit of ray.intersectObject(root,true)){let o=hit.object,visible=true,key;while(o){if(!o.visible)visible=false;if(groups[o.name]===o)key=o.name;o=o.parent;}if(!visible)continue;if(key)select(key);break;}});
window.demoInspect=()=>({ready:state.ready,errors:state.errors,selected,explode,isolation,replacements:[...replacements.keys()],groups:Object.fromEntries(Object.entries(groups).map(([k,g])=>[k,{visible:g.visible,position:g.position.toArray(),meshes:meshes(g).length,originalChildrenVisible:originals.get(k).children.every(o=>o.visible),uvRestored:originals.get(k).meshes.every(m=>{const a=m.geometry.attributes.uv?.array,b=m.userData.originalUV?.array;return (!a&&!b)||(a?.length===b?.length&&a.every((v,i)=>v===b[i]));}),colors:originals.get(k).meshes.map(m=>materials(m).map(a=>a.color?.getHexString())),wrapped:originals.get(k).meshes.some(m=>materials(m).some(a=>!!a.userData.previewMap))}]))});
try{manifest=(await (await fetch('./manifest.json')).json()).groups;const gltf=await loader.loadAsync('./Aprilia-RS660-split.glb',e=>$('#progress').textContent=e.total?Math.round(e.loaded/e.total*100)+'%':'读取模型…');root=gltf.scene;holder.add(root);root.updateMatrixWorld(true);const bb=new THREE.Box3().setFromObject(root),size=bb.getSize(new THREE.Vector3());scale=2.6/Math.max(size.x,size.y,size.z);holder.scale.setScalar(scale);holder.position.set(-(bb.min.x+bb.max.x)/2*scale,-bb.min.y*scale,-(bb.min.z+bb.max.z)/2*scale);root.updateMatrixWorld(true);
 for(const [key,row] of Object.entries(manifest)){const g=root.getObjectByName(key);if(!g)throw Error('缺少部件节点 '+key);groups[key]=g;const mm=meshes(g);originals.set(key,{position:g.position.clone(),children:[...g.children],meshes:mm});for(const m of mm){m.geometry=m.geometry.clone();m.userData.originalUV=m.geometry.attributes.uv?.clone();mats.set(m,materials(m).map(mat=>mat.clone()));m.material=materials(m).map(mat=>mat.clone());if(m.material.length===1)m.material=m.material[0];}const opt=document.createElement('option');opt.value=key;opt.textContent=row.label;$('#part').append(opt);}
 $('#count').textContent=Object.keys(groups).length+' 个外观部件组';$('#loading').hidden=true;$('#controls').inert=false;select('tank');resize();setView();state.ready=true;
}catch(e){state.errors.push(e.message);$('#loading').innerHTML='<b>模型加载失败</b>';const p=document.createElement('p');p.textContent=e.message;$('#loading').append(p);}
