import type { KnowledgeDocument } from '../knowledge-search.js';

/** 仅用于工程验证的合成知识数据，不可作为真实维修依据。 */
export const diagnosisDemoKnowledge: KnowledgeDocument[] = [
  {
    knowledgeId: 'manual-ninja400-cold-start',
    title: 'Ninja 400 服务手册：冷启动检查',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/ninja400-cold-start',
    content: '冷车启动困难或怠速熄火时，依次检查蓄电池电压、火花塞状态和节气门怠速空气通道。',
  },
  {
    knowledgeId: 'case-ninja400-cold-start',
    title: '故障案例：Ninja 400 冷车熄火',
    sourceType: 'fault-case',
    sourceUrl: 'https://example.com/cases/ninja400-cold-start',
    content: '冷车启动困难并伴随怠速熄火，案例排查发现蓄电池负载电压不足，清洁怠速空气通道后恢复。',
  },
  {
    knowledgeId: 'manual-battery-load-test',
    title: '维修手册：冷车启动蓄电池负载测试',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/battery-load-test',
    content: '冷车启动困难时，应测量蓄电池静态电压并执行负载测试，确认启动过程中的电压下降。',
  },
  {
    knowledgeId: 'case-spark-plug-cold-start',
    title: '故障案例：火花塞导致冷车启动困难',
    sourceType: 'fault-case',
    sourceUrl: 'https://example.com/cases/spark-plug-cold-start',
    content: '车辆冷车启动困难且怠速不稳，更换状态异常的火花塞并复核点火后恢复。',
  },
  {
    knowledgeId: 'manual-idle-air-channel',
    title: '维修手册：怠速空气通道检查',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/idle-air-channel',
    content: '出现冷车怠速熄火时，检查节气门体和怠速空气通道是否存在积碳或堵塞。',
  },
  {
    knowledgeId: 'manual-cb500x-brake',
    title: 'CB500X 服务手册：液压制动',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/cb500x-brake',
    content: '刹车手感变软、制动力下降时，检查制动液液位、管路泄漏，并按维修顺序排出系统空气。',
  },
  {
    knowledgeId: 'case-brake-soft',
    title: '故障案例：刹车手感变软',
    sourceType: 'fault-case',
    sourceUrl: 'https://example.com/cases/brake-soft',
    content: '刹车手感持续变软的案例中发现制动管路进入空气，排气并复核泄漏点后恢复。',
  },
  {
    knowledgeId: 'manual-brake-fluid',
    title: '维修手册：制动液与刹车手感检查',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/brake-fluid',
    content: '刹车手感变软或制动力下降时，检查制动液含水率、液位和更换周期。',
  },
  {
    knowledgeId: 'case-brake-hose-leak',
    title: '故障案例：制动软管泄漏',
    sourceType: 'fault-case',
    sourceUrl: 'https://example.com/cases/brake-hose-leak',
    content: '车辆刹车手感变软并伴随制动力下降，检查发现制动软管接头存在轻微泄漏。',
  },
  {
    knowledgeId: 'manual-brake-air-bleed',
    title: '维修手册：刹车系统排气',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/brake-air-bleed',
    content: '刹车手感变软时按规定顺序排出制动系统空气，并确认制动力恢复。',
  },
  {
    knowledgeId: 'manual-z400-cooling',
    title: 'Z400 服务手册：冷却系统',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/z400-cooling',
    content: '水温过高且风扇不转时，依次检查冷却液、保险丝、风扇继电器和电机供电。',
  },
  {
    knowledgeId: 'case-cooling-fan',
    title: '故障案例：高温时冷却风扇不转',
    sourceType: 'fault-case',
    sourceUrl: 'https://example.com/cases/cooling-fan',
    content: '车辆水温过高且冷却风扇不转，案例检查发现风扇继电器触点失效。',
  },
  {
    knowledgeId: 'manual-cooling-relay',
    title: '维修手册：高水温风扇继电器检查',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/cooling-relay',
    content: '水温过高且风扇不转时，测量风扇继电器控制信号和输出端供电。',
  },
  {
    knowledgeId: 'case-cooling-fuse',
    title: '故障案例：风扇保险丝熔断',
    sourceType: 'fault-case',
    sourceUrl: 'https://example.com/cases/cooling-fuse',
    content: '车辆水温过高后风扇不转，检查发现风扇保险丝熔断，并进一步排查电机电流。',
  },
  {
    knowledgeId: 'manual-coolant-level',
    title: '维修手册：高水温冷却液检查',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/coolant-level',
    content: '出现水温过高时检查冷却液液位、泄漏和循环状态，同时确认风扇能够正常运转。',
  },
  {
    knowledgeId: 'manual-duke390-chain',
    title: 'Duke 390 维护手册：传动链条',
    sourceType: 'manual',
    sourceUrl: 'https://example.com/manual/duke390-chain',
    content: '链条异响和收油顿挫通常需要检查松弛量、润滑状态与链轮磨损。',
  },
  {
    knowledgeId: 'catalog-demo-part',
    title: '测试配件目录',
    sourceType: 'part-catalog',
    sourceUrl: 'https://example.com/catalog/demo',
    content: '此条目用于验证配件目录不会进入故障知识召回。',
  },
];
